gnovelty: gnovelty_main_standalone.cc
	mpic++ -O3 -o gnovelty -g gnovelty_main_standalone.cc -static-libgcc -DNDEBUG -fno-strict-aliasing -fomit-frame-pointer -funroll-all-loops -fexpensive-optimizations -malign-double -Wall -march=nocona -ffast-math -lpthread -lglog 
