EXEC   = strengthener
BASE   = minisat
MROOT  = ..
DEPDIR = $(BASE)/mtl $(BASE)/utils $(BASE)/core
LFLAGS = -pthread
CFLAGS = -g -I$(MROOT)/$(BASE) -DMINIRED
OBJEXT = om

include $(MROOT)/strengthener/template.mk
