gnovelty: gnovelty_main_standalone_searcher.cc
	mpic++ -O3 -o gnovelty -g gnovelty_main_standalone_searcher.cc -static-libgcc -DNDEBUG -fno-strict-aliasing -fomit-frame-pointer -funroll-all-loops -fexpensive-optimizations -malign-double -Wall -march=nocona -ffast-math -lpthread -lglog 

clean:
	rm gnovelty

.PHONY: clean
